Add instructions for installation in arch linux
openhab/openhab-docs pull request #1297
Opened 2020-12-02 19:16 UTC by ChaosKid42

I created a AUR package description for arch linux. This PR adds the necessary documentation.

2020-12-10 21:44 UTC, Confectrician requested changes
Hey @ChaosKid42 thanks for your contribution. 👍 

I have one small comment, but then we are good to go. :)

2020-12-10 21:44 UTC, Confectrician commented on installation/linux.md
> +The Arch User Repository ([AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository)) is a community-driven repository for Arch users. It contains package descriptions (PKGBUILDs) that allow yo
```suggestion
The Arch User Repository ([AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository)) is a community-driven repository for Arch users. 
It contains package descriptions (PKGBUILDs) that allow you to compile a package from source with makepkg and then install it via pacman.
```

One line per sentence please.

2020-12-11 04:51 UTC, ChaosKid42 commented on installation/linux.md
> +The Arch User Repository ([AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository)) is a community-driven repository for Arch users. It contains package descriptions (PKGBUILDs) that allow yo
@Confectrician Sure. Done

2020-12-11 14:09 UTC, Confectrician approved these changes
Thanks. 👍

2020-12-11 14:10 UTC, merged