[WIP] Getting started tutorial
openhab/openhab-docs pull request #1304
Opened 2020-12-10 23:06 UTC by rkoshak

Created a folder and started copying and editing the Getting started tutorial from the forum. Comments and suggestions as I go are welcome.

This is a WIP. To do includes:

- [X] Introduction

- [X] First Steps

- [ ] Things: Simple

- [ ] Things: Intermediate

- [ ] Things: Advanced

- [ ] Items and the Semantic Model

- [ ] Persistence (Not yet written)

- [ ] Pages: Introduction

- [ ] Pages: Widgets (still needs a "build a custom widget" tutorial to be written)

- [ ] Pages: Page Types (still missing lots of content)
[Pages: Page Types]({{base}}/tutorials/getting_started/pages_types.html): Layout, Charts, and Tabbed type Pages

- [ ] Rules: Simple

- [ ] Rules: Intermediate (not yet written)

- [ ] openHAB Cloud (note yet written)

- [ ] Putting it all Together

2020-12-10 23:21 UTC, rkoshak commented
Hmmmm. I've no idea how to get to the pages through the preview build. I went to https://deploy-preview-1304--openhab-docs-preview.netlify.app/docs/tutorials/getting_started/intro.html and I get a 404. Any advice?

2020-12-11 01:02 UTC, ghys commented
@rkoshak please open `.vuepress/process_main_docs.rb` and:
- line 56: replace "beginner" with "getting_started"
- line 59: replace "beginner" with "getting_started"
- line 62: uncomment and replace "beginner" with "getting_started"

2020-12-11 01:06 UTC, ghys commented
Also in `.vuepress/docs-sidebar.js`:

You can uncomment the whole tutorial section (lines 38 to 51) __but__ make sure not to include children pages that don't exist (or the build will fail).
Also you can move the section up above the Concepts section like we discussed.

2020-12-11 17:55 UTC, rkoshak commented
Will do! I want to make sure to see the preview before transferring to much stuff over.

2020-12-11 19:29 UTC, ghys commented on .vuepress/process_main_docs.rb
> +        process_file("#{docs_source_dir}/tutorials/getting_started", file, "docs/tutorial", "#{$docs_repo_root}/tutorials/getting_started/#{file}")
Your link in the sidebar should link to `docs/tutorial` because it's where the tutorial files are copied ;)
(since there's only one tutorial)

2020-12-13 18:15 UTC, Confectrician commented
Ok. I have prepared and merged most of the small changes to the docs now.
I have to remove several pages now in the next step, which will probably break build (and preview) again.

Maybe we will have to rebase this PR then, to get the preview working or at least solve some merge conflicts before it will run again.

2020-12-15 23:51 UTC, rkoshak commented
The Persistence page I just pushed is wholly my writing and has not been reviewed. Anyone who has read many of my forum postings knows I need an editor. Please pay extra attention to that page when reviewing.

2020-12-17 11:19 UTC, jensflorian reviewed
`If you need to restoreOnStartup unsupported Item types, MapDB might be a better choice for you.`
I think you should provide at least one example: If you need to restoreOnStartup unsupported Item types (such as strings), MapDB...


`Why Bother with Persitence? ` -> Persistence

2020-12-19 19:08 UTC, Confectrician reviewed
I had a first look already, alltough this is WIP.

Images are checked so far and i have read through some articles too already.

![image](https://user-images.githubusercontent.com/7161177/102697390-c920c500-4235-11eb-99ee-949e17c965ab.png)

Well done so far. 👍

2020-12-19 19:08 UTC, Confectrician commented on tutorials/getting_started/index.md
> +This tutorial assumes users have read the concepts and installation guide already.
Maybe we should link those areas here.

2020-12-20 12:25 UTC, Confectrician commented on .vuepress/docs-sidebar.js
> +      ['tutorials/getting_started', "Getting Started"]
```suggestion
      ['tutorial/', "Getting Started"]
```

2020-12-20 12:29 UTC, Confectrician requested changes

2020-12-20 12:29 UTC, Confectrician commented on tutorials/getting_started/model.md
> +title:  - Semantic Model
```suggestion
title:  Semantic Model
```

2020-12-20 12:29 UTC, Confectrician commented on tutorials/getting_started/persistence.md
> +title:  - Persistence
```suggestion
title:  Persistence
```

2020-12-20 12:29 UTC, Confectrician commented on tutorials/getting_started/things_advanced.md
> +title:  - Adding Things - Advanced
```suggestion
title: Adding Things - Advanced
```

2020-12-20 12:29 UTC, Confectrician commented on tutorials/getting_started/things_intermediate.md
> +title:  - Adding Things - Intermediate
```suggestion
title: Adding Things - Intermediate
```

2020-12-20 12:29 UTC, Confectrician commented on tutorials/getting_started/things_simple.md
> +title:  - Adding Things - Simple
```suggestion
title: Adding Things - Simple
```

2020-12-20 12:30 UTC, Confectrician commented on tutorials/getting_started/persistence.md
> +title:  - Persistence
> 1:26:47 PM: YAMLException: end of the stream or a document separator is expected at line 2, column 9:
> 1:26:47 PM:     title:  - Persistence

Seems that the trailing dash is breaking the build

2020-12-20 17:02 UTC, Confectrician commented
Answerst to https://github.com/openhab/openhab-docs/issues/1133#issuecomment-748632648 from @bwosborne2 

This tutorial assuems reading concepts and installation articles before starting with it.
So this should already been covered with those prerequesites.

2020-12-20 17:19 UTC, Confectrician commented on tutorials/getting_started/index.md
> +This tutorial assumes users have read the concepts and installation guide already.
Changed my mind.

2020-12-20 20:17 UTC, Confectrician approved these changes

2020-12-20 20:18 UTC, merged