Document MainUI developer sidebar search abilities
openhab/openhab-docs pull request #2062
Opened 2023-04-09 19:18 UTC by florian-h05

With https://github.com/openhab/openhab-webui/pull/1732, the developer sidebar search was extended to check much more entities for the search string. This lists what is possible now.

2023-04-10 10:06 UTC, stefan-hoehn requested changes

2023-04-10 10:06 UTC, stefan-hoehn commented on tutorials/getting_started/tips-and-tricks.md
> +In the searchbox at the top, enter a search term which can be part of an object's name, ID, label, etc.
Enter a search term in the search field at the top to search within Items, Things, Rules and Pages. The search term can be part of an object's name, ID, label, etc.

2023-04-10 10:06 UTC, stefan-hoehn commented on tutorials/getting_started/tips-and-tricks.md
> +- Rules, Scenes & Scripts:
Aren't you missing the Things here?

2023-04-10 13:34 UTC, stefan-hoehn approved these changes
LGTM, thanks @florian-h05

2023-04-10 13:35 UTC, merged

2023-04-10 14:41 UTC, rkoshak commented
I'm sorry I missed reviewing this before it got merged. 

> The developer sidebar is checking your search query non case-intensive against the following entities:

What is meant by this sentence? That the search ignores case or that case matters in the search?

If the former "non case-intensive" should be changed to "case-insensitive". If the latter it should change to "case-sensitive".

I can file a quick PR but as written I'm not sure which is correct.

2023-04-10 17:29 UTC, florian-h05 commented
The search ignores case, so typing `ITEM` you can find any `item` or `ItEm` etc.

2023-04-10 18:04 UTC, rkoshak commented
> PS: Always good to have a native English speaker reading this. We learn English in school, but the vocabulary we learn is limited to the basics and the topics we talk about - case-insensitive etc. is not a part of it.

Totally understand. Sadly we rarely have opportunity to really study another language in school. My Spanish is so poor and atrophied I might be able to get through a children's board book and no more.

Sometime later today or tomorrow I'll submit a quick PR if I can't get to it in the next half hour or so.

I wonder if using the less technical 

> The developer sidebar will search against the following entities, ignoring case:

"case-sensitive" and "case-insensitive" is more used as a technical term in computer programming than in common spoken English.

2023-04-11 09:05 UTC, florian-h05 commented
> Sadly we rarely have opportunity to really study another language in school. My Spanish is so poor and atrophied I might be able to get through a children's board book and no more.

We have more choice here, I had to chose between French and Latin (I chose Latin because of it was presented much better than French, and it is practical because many words in many languages a derived from Latin), and later we had to chose between „science and technology“ and Spanish, I chose science and technology. The other school in the city offers. Greece instead of Spanish.

> The developer sidebar will search against the following entities, ignoring case:

Sound much better than the technical terms!