Update rules-dsl.md
openhab/openhab-docs pull request #2187
Opened 2023-12-26 21:05 UTC by JensHauser

Learnings from conversation with Rich added:
https://community.openhab.org/t/ecma-rule-to-trigger-after-system-fully-functional/152091/6

Signed-off-by: Jens Hauser<jens@hauser-digital.de>

2023-12-27 15:47 UTC, stefan-hoehn requested changes
Many thanks for the contribution, Jens. See my comments.

2023-12-27 15:47 UTC, stefan-hoehn commented on configuration/rules-dsl.md
> +A rule triggering for a startlevel and being saved during development, will be reloaded.
A rule that triggers for a start level and is saved during development is reloaded.

2023-12-27 15:47 UTC, stefan-hoehn commented on configuration/rules-dsl.md
> +Writing rules with quite low startlevels might be too early, as for instance not all things are online yet.
This quite generic and more or less stating the obvious. Can you provide an example here to make it more tangible?

2023-12-30 16:17 UTC, JensHauser commented
Hi Stefan, hope, it fits now. Happy new year soon :-)

2023-12-31 09:04 UTC, stefan-hoehn approved these changes
Thanks for the contribution.

2023-12-31 09:04 UTC, merged