Create a new doc page for Main UI‘s special features
openhab/openhab-docs pull request #2188
Opened 2023-12-27 11:54 UTC by florian-h05

2023-12-27 12:17 UTC, florian-h05 commented
Preview: https://deploy-preview-2188--openhab-docs-preview.netlify.app/docs/ui/mainui.html

@digitaldan FYI this adds the docs for the UI command Item.

2023-12-27 15:53 UTC, digitaldan approved these changes
Thanks @florian-h05 !!!!!

2023-12-27 15:53 UTC, digitaldan commented on ui/mainui.md
> +Main UI implements a web audio sink, which means the openHAB server can play audio through on a client device through the browser.
```suggestion
Main UI implements a web audio sink which allows the openHAB server to play audio through the web browser.
```

2023-12-27 15:58 UTC, stefan-hoehn requested changes

2023-12-27 15:58 UTC, stefan-hoehn commented on ui/mainui.md
> +  Naviate back.
Navigate

2023-12-27 16:03 UTC, stefan-hoehn requested changes

2023-12-27 16:03 UTC, stefan-hoehn commented on settings/aboutpage.md
> -- This setting is also part of the miscellaneous settings.
From here on:

I have the feeling you deleted most of what I have written here. Please don't as I have put quite an amount of work by providing context, background and examples into it.

You move around redundant information but don't drop it, thanks.

2023-12-27 16:53 UTC, florian-h05 commented on ui/building-pages.md
> +Expressions can be tested in the Widgets Expression Tester found in the [Developer Sidebar]({{base}}/docs/ui/mainui.html#developer-sidebar) (<kbd>Alt</kbd><kbd>Shift</kbd><kbd>D</kbd>).
Fixed (commit not yet pushed).
However this has to be changed anyway when my other PR is merged, we will run into merge conflicts I will have to resolve then.

2023-12-27 20:24 UTC, stefan-hoehn commented on ui/mainui.md
> +- `notification:$text:$title:$subtitle:$titleRight:$closeTimeout`:
Then would you mind adding this as an example or mention this?

2023-12-27 23:01 UTC, florian-h05 commented on ui/mainui.md
> +- `notification:$text:$title:$subtitle:$titleRight:$closeTimeout`:
I’ve added this sentence here:

> To leave out a parameter, leave a colon space empty, e.g. `notification:$text:$title:::$closeTimeout`.

Should I still add an example?

2023-12-31 15:19 UTC, stefan-hoehn commented on ui/mainui.md
> +- `notification:$text:$title:$subtitle:$titleRight:$closeTimeout`:
No, that's fine.

2023-12-31 16:22 UTC, florian-h05 commented on ui/building-pages.md
> +Expressions can be tested in the Widgets Expression Tester found in the [Developer Sidebar]({{base}}/docs/ui/mainui.html#developer-sidebar) (<kbd>Alt</kbd><kbd>Shift</kbd><kbd>D</kbd>).
I have just rebased the PR, this comment is resolved since the section doesn't exist anymore on that page.

2024-01-03 13:46 UTC, closed without merging

2024-01-03 13:46 UTC, florian-h05 commented
Superseded by #2198.