configuration/items: use more specific item types
openhab/openhab-docs pull request #2195
Opened 2024-01-01 13:39 UTC by dilyanpalauzov

I think having all examples using as specific item types, as possible, utilizing the default UoM, is a good practice.

The wording “If no state presentation and no square brackets are given…” leaves unclear what happens, if state presentation is missing, but square brackets are present.  This is refined here.

Alternative good wordings will be just “If no state presentation is given”, or “If no square brackets are given”.

2024-01-01 13:56 UTC, dilyanpalauzov commented
The information about what happens, when the square brackets are absent, is not universally correct:
* As explained at https://github.com/openhab/openhab-webui/issues/2251 missing `[%s]` implies not shown values in Basic UI, but
* [The example for `systembining`](https://www.openhab.org/addons/bindings/systeminfo/#example) suggest not to use state presentation/square brackets, and it still shows the current values (I tried only with `CPU_Load5`)

2024-01-02 08:53 UTC, stefan-hoehn requested changes

2024-01-02 08:53 UTC, stefan-hoehn commented on configuration/items.md
> +If no state presentation is given, or there is no text between the square brackets, the the Item will not provide a textual presentation of its internal state (i.e. in UIs no state is shown).
the the

2024-01-07 10:03 UTC, stefan-hoehn approved these changes
LGTM now.

2024-01-07 10:03 UTC, merged