Add Main UI docs for integration into sidebar help
openhab/openhab-docs pull request #2199
Opened 2024-01-03 13:38 UTC by florian-h05

/cc @stefan-hoehn @Confectrician 

Please have a look at the CONTRIBUTING.md inside the mainui folder.

2024-01-03 13:40 UTC, florian-h05 commented
I have now migrated all content that was hard-coded into the UI to the docs repo and created the structure for the new Main UI docs. You can run my linked UI PR locally to see how the UI integrates the docs.

Feel free to extend the documentation, migrate docs from elsewhere in this repo and put some content into the empty files.

2024-01-26 21:19 UTC, stefan-hoehn requested changes
@florian-h05 This is an amazing contribution to the docs and you earn the docs gold medal for the month 🥇 🤩

Given the amount of text you contributed I only found only a few minor issues.

2024-01-26 21:19 UTC, stefan-hoehn commented on mainui/settings/scenes.md
> +<!-- END MAINUI SIDEBAR DOC - DO NOT REMOVE -->
```
<!-- END MAINUI SIDEBAR DOC - DO NOT REMOVE -->

A comprehensive introduction to scenes can be found at the 
[scenes tutorial]({{base}}/tutorial/rules_scenes.html).
```

2024-01-26 21:19 UTC, stefan-hoehn commented on mainui/settings/schedule.md
> +this rule will be shown in the calendar view on this page.
then this

2024-01-26 21:19 UTC, stefan-hoehn commented on mainui/settings/schedule.md
> +A rule that is schedule repeatedly like everyday at 8:00 in the morning will therefore be shown on every day of the calendar view.
A rule that is scheduled repeatedly

2024-01-26 21:19 UTC, stefan-hoehn commented on mainui/settings/scripts.md
> +They can be used to reuse code and logic across multiple other rules, one off experimentation to figure something out, create a catalog of examples, or to drive tests for other rules and behaviors.
for experimentation to figure

2024-01-26 21:19 UTC, stefan-hoehn commented on mainui/settings/things.md
> +  Click on any Thing in the list to see its configuration page and it's channels.
its channels.

2024-01-26 21:19 UTC, stefan-hoehn commented on mainui/settings/things.md
> +All Discovery Results are put into the Thing inbox, from where they can be easily added to openHAB with just a few clicks.
Thing inbox from where they can be

2024-01-26 21:19 UTC, stefan-hoehn commented on mainui/settings/transformations.md
> +**Transformations** convert a value or Item state into different value or state.
into a different value

2024-01-26 22:57 UTC, florian-h05 commented on mainui/CONTRIBUTING.md
> +  - `<!--F7 $iconame -->`, where `$iconname` is a Framework7 icon's name
It is one n missing in `$iconame` ;-)

2024-01-26 23:05 UTC, florian-h05 commented on mainui/settings/persistence.md
> +To change this behaviour, you already found the correct page!
![image](https://github.com/openhab/openhab-docs/assets/73423173/c2bc26fe-1238-47e6-a84c-afbf033df2d8)

2024-01-26 23:07 UTC, florian-h05 commented on mainui/settings/rules.md
> +The page has a searchable list of rules where the following attributes
Great that you review your own contribution ;-)
I have only moved that from the old location to the new location, I haven't written this.

2024-01-26 23:15 UTC, florian-h05 commented
@stefan-hoehn Thank you for your fast review of this big PR!! I have addressed your review.

> This is an amazing contribution to the docs and you earn the docs gold medal for the month 🥇 🤩

Thank you very much, I guess I will share it with you since you wrote large parts of the docs that I moved around, and with @JustinGeorgi, who originally wrote what has been added to the UI and what I migrated to the docs repo.

2024-01-26 23:34 UTC, stefan-hoehn approved these changes
Thanks, looks good now.

2024-01-26 23:35 UTC, merged

2024-02-02 09:09 UTC, florian-h05 commented
@ghys @Confectrician Why can’t I find that documentation changes on https://next.openhab.org/docs?

2024-02-06 15:30 UTC, ghys commented
The website fails to build on Netlify since Jan 26th:
https://app.netlify.com/sites/openhab-next/deploys/65c1516267c7c40008971007
with this error:
```
10:22:45 PM: /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:1225:in `stat": No such file or directory @ rb_file_s_stat - .vuepress/openhab-docs/settings/images (Errno::ENOENT)
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:1225:in `lstat"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:1254:in `copy"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:416:in `block in copy_entry"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:1388:in `wrap_traverse"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:413:in `copy_entry"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:391:in `block in cp_r"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:1461:in `block in fu_each_src_dest"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:1477:in `fu_each_src_dest0"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:1459:in `fu_each_src_dest"
	from /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:390:in `cp_r"
	from prepare-docs.rb:359:in `<main>"
```
corresponding to this line in prepare-docs.rb:
https://github.com/openhab/website/blob/31c746e62fa4c3d5a3fc33c070713acfd2dd308c/prepare-docs.rb#L359

2024-02-06 18:46 UTC, florian-h05 commented
https://github.com/openhab/website/pull/445 will fix the website build.