Adding repository location to the addons tutorial
openhab/openhab-docs pull request #2304
Opened 2024-06-02 22:57 UTC by Mythobeast

Adding repository location to the addons tutorial

2024-06-06 06:07 UTC, stefan-hoehn requested changes

2024-06-06 06:07 UTC, stefan-hoehn commented on developers/index.md
> +documentation, in the [Contribuiting](https://www.openhab.org/docs/developer/contributing.html) section.
type in Contribuiting and please don't use absolute links. Use the following instead.

``
[Contributing](contributing.html) section.
``

2024-06-07 09:53 UTC, florian-h05 commented on developers/index.md
> +OpenHAB has [several repositories](https://github.com/openhab) on GitHub. You can find a list of them in the Developer Appendix of this
```suggestion
openHAB has [several repositories](https://github.com/openhab) on GitHub.
The most important ones are listed in the [Contribution section of the Developer Appendix](contributing.html#the-repositories). 
```

2024-06-07 09:55 UTC, florian-h05 commented on developers/index.md
> +documentation, in the [Contribuiting](https://www.openhab.org/docs/developer/contributing.html) section.
```suggestion
```

Remove this line, see comment above.

2024-06-07 09:56 UTC, florian-h05 commented on developers/index.md
> +For this tutorial, you'll want to clone the [OpenHAB-addons](https://github.com/openhab/openhab-addons) repository.
```suggestion
For this tutorial, you'll need to fork the [openhab-addons](https://github.com/openhab/openhab-addons) repository (press the fork button in GitHub) and then clone your fork.
```

2024-12-01 09:23 UTC, florian-h05 commented
Superseded by #2415.

@Mythobeast Thanks for your contribution, I have picked up your changes in #2415.
@stefan-hoehn Please close this PR.

2024-12-01 10:41 UTC, closed without merging

2024-12-01 10:41 UTC, stefan-hoehn commented
closing PR