Improve `ThingActions` docs for UI-based rules & REST API support
openhab/openhab-docs pull request #2416
Opened 2024-12-01 11:50 UTC by florian-h05

2024-12-01 11:50 UTC, florian-h05 commented
@lolodomo Can you please have a look?

2024-12-14 08:25 UTC, lolodomo requested changes
All this looks very good. I just noticed a forgotten possible type for output.

2024-12-14 08:25 UTC, lolodomo commented on developers/bindings/index.md
> +- all primitive types, e.g. `boolean`, `int`, `float`, `String`, and their boxed counterparts
Please add missing BigDecimal

2024-12-14 08:38 UTC, lolodomo commented
@florian-h05 @holgerfriedrich : that would be great to merge before releasing version 4.3.

2024-12-14 08:49 UTC, florian-h05 commented on developers/bindings/index.md
> +- all primitive types, e.g. `boolean`, `int`, `float`, `String`, and their boxed counterparts
Just added, thanks for the catch.

2024-12-14 10:30 UTC, holgerfriedrich commented
@lolodomo sorry, can't help here, this is docs repo.... I can only merge in core repo.

2024-12-14 10:31 UTC, florian-h05 commented
Ping @stefan-hoehn

2024-12-14 12:51 UTC, stefan-hoehn approved these changes
LGTM

2024-12-14 12:51 UTC, merged