doc: Added web socket
openhab/openhab-docs pull request #2437
Opened 2024-12-30 12:06 UTC by FSeidinger

To get the nginx proxy working with web sockets, e.g. to use the new log viewer in the OH4 GUI, the proxy_http_version 1.1 was added to the nginx configuration.

For hints see [Openhab 4.x and log viewer behind nginx proxy](https://community.openhab.org/t/openhab-4-x-and-log-viewer-behind-nginx-proxy/161222)

2024-12-31 10:48 UTC, stefan-hoehn commented
@mstormi @ecdye Do you mind reviewing the content from your experience?

2024-12-31 10:54 UTC, mstormi commented
I've added HTTP/1.1 to openHABian's default nginx config, but I have not tested it.
So I cannot comment if that works hence I won't.

2024-12-31 10:55 UTC, florian-h05 requested changes
One change, other than this LGTM.

2024-12-31 10:55 UTC, florian-h05 commented on installation/reverse-proxy.md
> +    proxy_http_version                        1.1;
This doesn’t need to be set here, already set in the location block below, please revert.

2025-07-15 12:56 UTC, lolodomo commented
@FSeidinger : can you please look at @florian-h05 comment and adjust?

2026-04-10 11:17 UTC, stefan-hoehn commented
@florian-h05 Should I just apply you recommended change and merge it?

2026-04-10 11:31 UTC, florian-h05 commented
I have to check what this was about, will let you know once I am done.

2026-04-10 12:48 UTC, florian-h05 commented on installation/reverse-proxy.md
> +    # Enable web sockets, e.g. used by the log viewver in the new OH4 GUI
Please also remove this comment line, it has typos and IMO isn’t needed.

2026-04-11 08:53 UTC, florian-h05 approved these changes

2026-04-11 11:12 UTC, merged